export const TOGGLE_CART_ACTION = 'TOGGLE_CART';
export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART';
export const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART';
export const SET_ITEM_QUANTITY = 'SET_ITEM_QUANTITY';
export const EMPTY_CART = 'EMPTY_CART';

export const REQUEST_PRODUCT_LIST_ACTION = 'REQUEST_PRODUCT_LIST';
export const FILL_PRODUCT_LIST_ACTION = 'FILL_PRODUCT_LIST';
export const FAIL_PRODUCT_LIST_ACTION = 'FAIL_PRODUCT_LIST';
export const CATEGORY_FILTER_PRODUCT_LIST = 'CATEGORY_FILTER_PRODUCT_LIST';

export const REQUEST_CATEGORY_LIST_ACTION = 'REQUEST_CATEGORY_LIST';
export const FILL_CATEGORY_LIST_ACTION = 'FILL_CATEGORY_LIST';
export const FAIL_CATEGORY_LIST_ACTION = 'FAIL_CATEGORY_LIST';

export const REQUEST_USER_REGISTER = 'REQUEST_USER_REGISTER';
export const SUCESS_USER_REGISTER = 'SUCESS_USER_REGISTER';
export const FAIL_USER_REGISTER = 'FAIL_USER_REGISTER';

export const REQUEST_USER_LOGIN = 'REQUEST_USER_LOGIN';
export const SUCESS_USER_LOGIN = 'SUCESS_USER_LOGIN';
export const FAIL_USER_LOGIN = 'FAIL_USER_LOGIN';
export const JWT_USER_LOGOUT = 'JWT_USER_LOGOUT';

export const LOGGED_PASSWORD_RESET_REQUEST = 'LOGGED_PASSWORD_RESET_REQUEST';
export const LOGGED_PASSWORD_RESET_SUCESS = 'LOGGED_PASSWORD_RESET_SUCESS';
export const LOGGED_PASSWORD_RESET_FAIL = 'LOGGED_PASSWORD_RESET_FAIL';

export const USERNAME_RESET_REQUEST = 'USERNAME_RESET_REQUEST';
export const USERNAME_RESET_SUCESS = 'USERNAME_RESET_SUCESS';
export const USERNAME_RESET_FAIL = 'USERNAME_RESET_FAIL';

export const EMAIL_RESET_REQUEST = 'EMAIL_RESET_REQUEST';
export const EMAIL_RESET_SUCESS = 'EMAIL_RESET_SUCESS';
export const EMAIL_RESET_FAIL = 'EMAIL_RESET_FAIL';

export const DELETE_DIRECTION_REQUEST = 'DELETE_DIRECTION_REQUEST';
export const DELETE_DIRECTION_SUCESS = 'DELETE_DIRECTION_SUCESS';
export const DELETE_DIRECTION_FAIL = 'DELETE_DIRECTION_FAIL';

export const ADD_DIRECTION_REQUEST = 'ADD_DIRECTION_REQUEST';
export const ADD_DIRECTION_SUCESS = 'ADD_DIRECTION_SUCESS';
export const ADD_DIRECTION_FAIL = 'ADD_DIRECTION_FAIL';

export const GET_DIRECTIONS_REQUEST = 'GET_DIRECTIONS_REQUEST';
export const GET_DIRECTIONS_SUCESS = 'GET_DIRECTIONS_SUCESS';
export const GET_DIRECTIONS_FAIL = 'GET_DIRECTIONS_FAIL';

export const GET_ORDERS_REQUEST = 'GET_ORDERS_REQUEST';
export const GET_ORDERS_SUCESS = 'GET_ORDERS_SUCESS';
export const GET_ORDERS_FAIL = 'GET_ORDERS_FAIL';

export const PASSWORD_RESET_REQUEST = 'PASSWORD_RESET_REQUEST';
export const PASSWORD_RESET_SUCESS = 'PASSWORD_RESET_SUCESS';
export const PASSWORD_RESET_FAIL = 'PASSWORD_RESET_FAIL';

export const PASSWORD_CONFIRM_RESET_REQUEST = 'PASSWORD_CONFIRM_RESET_REQUEST';
export const PASSWORD_CONFIRM_RESET_SUCESS = 'PASSWORD_CONFIRM_RESET_SUCESS';
export const PASSWORD_CONFIRM_RESET_FAIL = 'PASSWORD_CONFIRM_RESET_FAIL';

export const TOGGLE_POP_UP = 'TOGGLE_POP_UP';

export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST';
export const CREATE_ORDER_SUCESS = 'CREATE_ORDER_SUCESS';
export const CREATE_ORDER_FAIL = 'CREATE_ORDER_FAIL';
