export const TOGGLE_CART_ACTION = 'TOGGLE_CART';

export const REQUEST_PRODUCT_LIST_ACTION = 'REQUEST_PRODUCT_LIST';
export const FILL_PRODUCT_LIST_ACTION = 'FILL_PRODUCT_LIST';
export const FAIL_PRODUCT_LIST_ACTION = 'FAIL_PRODUCT_LIST';

export const REQUEST_CATEGORY_LIST_ACTION = 'REQUEST_CATEGORY_LIST';
export const FILL_CATEGORY_LIST_ACTION = 'FILL_CATEGORY_LIST';
export const FAIL_CATEGORY_LIST_ACTION = 'FAIL_CATEGORY_LIST';

