export const TOGGLE_CART_ACTION = 'TOGGLE_CART';

export const REQUEST_PRODUCT_LIST_ACTION = 'REQUEST_PRODUCT_LIST';
export const FILL_PRODUCT_LIST_ACTION = 'FILL_PRODUCT_LIST';
export const FAIL_PRODUCT_LIST_ACTION = 'FAIL_PRODUCT_LIST';
export const CATEGORY_FILTER_PRODUCT_LIST = 'CATEGORY_FILTER_PRODUCT_LIST';

export const REQUEST_CATEGORY_LIST_ACTION = 'REQUEST_CATEGORY_LIST';
export const FILL_CATEGORY_LIST_ACTION = 'FILL_CATEGORY_LIST';
export const FAIL_CATEGORY_LIST_ACTION = 'FAIL_CATEGORY_LIST';

export const REQUEST_USER_REGISTER = 'REQUEST_USER_REGISTER';
export const SUCESS_USER_REGISTER = 'SUCESS_USER_REGISTER';
export const FAIL_USER_REGISTER = 'FAIL_USER_REGISTER';

export const REQUEST_USER_LOGIN = 'REQUEST_USER_LOGIN';
export const SUCESS_USER_LOGIN = 'SUCESS_USER_LOGIN';
export const FAIL_USER_LOGIN = 'FAIL_USER_LOGIN';
export const JWT_USER_LOGOUT = 'JWT_USER_LOGOUT';

export const PASSWORD_RESET_REQUEST = 'PASSWORD_RESET_REQUEST';
export const PASSWORD_RESET_SUCESS = 'PASSWORD_RESET_SUCESS';
export const PASSWORD_RESET_FAIL = 'PASSWORD_RESET_FAIL';

export const PASSWORD_CONFIRM_RESET_REQUEST = 'PASSWORD_CONFIRM_RESET_REQUEST';
export const PASSWORD_CONFIRM_RESET_SUCESS = 'PASSWORD_CONFIRM_RESET_SUCESS';
export const PASSWORD_CONFIRM_RESET_FAIL = 'PASSWORD_CONFIRM_RESET_FAIL';

export const TOGGLE_POP_UP = 'TOGGLE_POP_UP';
